"""Add active_timers to devices

Revision ID: 5f278b0035b9
Revises: 83934f95dbdd
Create Date: 2025-12-03 20:24:11.867969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f278b0035b9'
down_revision: Union[str, Sequence[str], None] = '83934f95dbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('active_timers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'active_timers')
    # ### end Alembic commands ###
