"""Add custom_topics to mqtt_config

Revision ID: 696e6dfd7c27
Revises: fe3586b48316
Create Date: 2025-12-02 09:11:32.906271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696e6dfd7c27'
down_revision: Union[str, Sequence[str], None] = 'fe3586b48316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_config', sa.Column('custom_topics', sa.JSON(), nullable=True))
    op.alter_column('mqtt_config', 'broker_host',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mqtt_config', 'broker_host',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('mqtt_config', 'custom_topics')
    # ### end Alembic commands ###
