"""Add switch_labels to devices

Revision ID: 83934f95dbdd
Revises: 0e5feed04079
Create Date: 2025-12-03 20:10:34.637923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83934f95dbdd'
down_revision: Union[str, Sequence[str], None] = '0e5feed04079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('switch_labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'switch_labels')
    # ### end Alembic commands ###
