"""Add schedules and notification_config tables

Revision ID: b3a2f7c00e19
Revises: fe3586b48316
Create Date: 2026-04-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a2f7c00e19'
down_revision: Union[str, Sequence[str], None] = '5f278b0035b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_config_id'), 'notification_config', ['id'], unique=False)
    
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('switch_name', sa.String(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('duration_unit', sa.String(), nullable=True),
    sa.Column('interval_value', sa.Integer(), nullable=True),
    sa.Column('interval_unit', sa.String(), nullable=True),
    sa.Column('total_duration_value', sa.Integer(), nullable=True),
    sa.Column('total_duration_unit', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_notification_config_id'), table_name='notification_config')
    op.drop_table('notification_config')
    # ### end Alembic commands ###
